include:
  - docker-compose.dev.common.yaml

services:
  backend:
    image: ghcr.io/damap-org/damap-backend:next
    build:
      context: ../
    restart: unless-stopped
    environment:
      QUARKUS_PROFILE: ${QUARKUS_PROFILE}
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://damap-db:5432/damap"
      QUARKUS_DATASOURCE_DB_KIND: "postgresql"
      QUARKUS_DATASOURCE_USERNAME: ${QUARKUS_DATASOURCE_USERNAME:-damap}
      QUARKUS_DATASOURCE_PASSWORD: ${QUARKUS_DATASOURCE_PASSWORD:-pw4damap}
    volumes:
      - ./tenants.yaml:/opt/damap/tenants.yaml:ro
    depends_on:
      db:
        condition: service_started
      keycloak:
          condition: service_healthy
      api-mock:
        condition: service_started
      fits:
        condition: service_started
    networks:
      default:
        aliases:
          - damap-be
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health/live" ]
      interval: 30s
      timeout: 15s
      retries: 5

  db:
    image: postgres:16
    pull_policy: always
    restart: unless-stopped
    environment:
      POSTGRES_USER: damap
      POSTGRES_PASSWORD: pw4damap
      POSTGRES_DB: damap
    ports:
      - "8088:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - damap-db
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U damap -d damap'" ]
      interval: 30s
      timeout: 15s
      retries: 5

volumes:
  pg-data:
