namespace: damap
openshift: false
debug: false
damap:
  frontend_image: "ghcr.io/damap-org/damap-frontend:next"
  backend_image: "ghcr.io/damap-org/damap-backend:next"
  db_name: damap
  db_user: damap
  db_password: pw4damap
  hostname: damap.localhost
  protocol: http
  storage_class_name: ""
keycloak:
  admin_user: admin
  admin_password: admin
  db_name: keycloak
  db_user: keycloak
  db_password: keycloak
  hostname: keycloak.localhost
  protocol: http
  storage_class_name: ""
# Create a custom backend build using the OpenShift CI pipeline.
# Sadly, this doesn't work in vanilla Kubernetes.
custom_build:
  name: ""
  repo: https://github.com/damap-org/damap-backend
  ref: "next"
pure:
  enabled: false
  persons_data: {}
  projects_data: {}
  description_classification: "/dk/atira/pure/..."
  project_lead_classification: "/dk/atira/pure/..."
  role_classifications: {}
