include:
  - docker-compose.postgres.yaml

services:
  damap-be:
    environment:
      # configure these environment variables for your institution's PURE instance
      DAMAP_ELSEVIER_PURE_BACKEND: "http"
      DAMAP_ELSEVIER_PURE_ENDPOINT_URL: "https://your-pure-instance.elsevierpure.com/ws/api"
      DAMAP_ELSEVIER_PURE_API_KEY: "your-pure-api-key-here"
      
      # customize for your institution's PURE setup
      DAMAP_ELSEVIER_PURE_CONTRIBUTOR_ROLE_CLASSIFICATIONS: '{"\/dk\/atira\/pure\/member": "PROJECT_MEMBER", "\/dk\/atira\/pure\/projectlead": "PROJECT_LEADER"}'
      # project service config  
      DAMAP_PROJECTS_SERVICE: "elsevier-pure" 