tenants: ['tenant_1', 'tenant_2']
"%multitenant":
  quarkus:
    datasource:
      tenant_1:
        jdbc:
          url: jdbc:postgresql://damap-db:5432/tenant_1
      tenant_2:
        jdbc:
          url: jdbc:postgresql://damap-db:5432/tenant_2

    liquibase:
      tenant_1:
        migrate-at-start: true
        change-log: org/damap/base/db/changeLog-root.yaml
      tenant_2:
        migrate-at-start: true
        change-log: org/damap/base/db/changeLog-root.yaml