tenants: ['tuwien_ac_at']
"%multitenant":
  quarkus:
    datasource:
      tuwien_ac_at:
        jdbc:
          url: jdbc:postgresql://localhost:8088/tuwien_ac_at
          driver: org.postgresql.Driver
        db-kind: postgresql
        username: damap
        password: pw4damap

    liquibase:
      tuwien_ac_at:
        migrate-at-start: true
        change-log: org/damap/base/db/changeLog-root.yaml