## This file contains a production-grade setup of DAMAP as a Docker Compose file.
# NOTE: You should still review the security aspects of the setup before using it in production!

name: damap

include:
  - docker-compose.db.yaml
  - docker-compose.keycloak.yaml

services:
  backend:
    image: ghcr.io/damap-org/damap-backend:next
    restart: unless-stopped
    environment:
      DAMAP_ENV: PROD
      DAMAP_TITLE: ${DAMAP_TITLE:-DAMAP Tool}
      # --- Database settings --- #
      DAMAP_DATASOURCE_URL: "jdbc:postgresql://${DAMAP_DATABASE_HOST:-damap-db}:5432/${DAMAP_DATABASE_NAME?The DAMAP database name is required}"
      DAMAP_DATABASE_DB_KIND: "postgresql"
      DAMAP_DATASOURCE_USERNAME: "${DAMAP_DATABASE_USERNAME?The DAMAP datasource username is required}"
      DAMAP_DATASOURCE_PASSWORD: "${DAMAP_DATABASE_PASSWORD?The DAMAP datasource password is required}"
      # --- OIDC / Auth settings --- #
      DAMAP_ORIGINS: "${DAMAP_ORIGINS?The DAMAP origins setting is required}"
      DAMAP_AUTH_BACKEND_URL: "${DAMAP_AUTH_BACKEND_URL?The OIDC URL is required}"
      DAMAP_AUTH_FRONTEND_URL: "${DAMAP_AUTH_FRONTEND_URL?The OIDC URL is required}"
      DAMAP_AUTH_BACKEND_CLIENT: "${DAMAP_AUTH_BACKEND_CLIENT?The OIDC client ID is required}"
      DAMAP_AUTH_FRONTEND_CLIENT: "${DAMAP_AUTH_FRONTEND_CLIENT?The OIDC client ID is required}"
      # --- DAMAP PURE integration defaults --- #
      DAMAP_ELSEVIER_PURE_BACKEND: ${DAMAP_ELSEVIER_PURE_BACKEND:-file}
      DAMAP_ELSEVIER_PURE_ENDPOINT_URL: ${DAMAP_ELSEVIER_PURE_ENDPOINT_URL:-""}
      DAMAP_ELSEVIER_PURE_ENABLED: ${DAMAP_ELSEVIER_PURE_ENABLED:-true}
      DAMAP_ELSEVIER_PURE_PERSONS_FILE: ${DAMAP_ELSEVIER_PURE_PERSONS_FILE:-file:////opt/damap/config/pure-persons-data.json}
      DAMAP_ELSEVIER_PURE_PROJECTS_FILE: ${DAMAP_ELSEVIER_PURE_PROJECTS_FILE:-file:////opt/damap/config/pure-projects-data.json}
      # --- Settings needed for DAMAP to use the Person and Projects services --- #
      DAMAP_PERSON_SERVICES: ${DAMAP_PERSON_SERVICES:-[{"display-text":"Pure","query-value":"PURE","class-name":"org.damap.base.integration.pure.PurePersonService"},{"display-text":"ORCID","query-value":"ORCID","class-name":"org.damap.base.integration.orcid.ORCIDPersonServiceImpl"}]}
      DAMAP_PROJECTS_SERVICE: ${DAMAP_PROJECTS_SERVICE:-elsevier-pure}

      QUARKUS_LOG_CATEGORY__IO_SMALLRYE_JWT_AUTH__LEVEL: DEBUG
      QUARKUS_LOG_CATEGORY__IO_SMALLRYE_JWT__LEVEL: DEBUG
      QUARKUS_LOG_CATEGORY__IO_QUARKUS__LEVEL: DEBUG
      QUARKUS_LOG_CATEGORY__ORG_ECLIPSE_MICROPROFILE__LEVEL: DEBUG
      QUARKUS_LOG_CATEGORY__ORG_JBOSS_RESTEASY_REACTIVE__LEVEL: DEBUG
    expose:
      - 8080
    configs:
      - source: pure-persons-data
        target: ${DAMAP_ELSEVIER_PURE_PERSONS_FILE:-/opt/damap/config/pure-persons-data.json}
      - source: pure-projects-data
        target: ${DAMAP_ELSEVIER_PURE_PROJECTS_FILE:-/opt/damap/config/pure-projects-data.json}
    depends_on:
      db:
        condition: service_healthy
        required: false # We don't require this since the DB only exists when the with_db profile is enabled.
      keycloak:
        condition: service_healthy
        required: false # We don't require this since the DB only exists when the with_keycloak profile is enabled.
    networks:
      damap-internal:
        aliases:
          - damap-be
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health/live" ]
      start_period: 120s
      interval: 30s
      timeout: 15s
      retries: 5

  frontend:
    image: ghcr.io/damap-org/damap-frontend:next
    restart: unless-stopped
    expose:
      - 8080
    depends_on:
      backend:
        condition: service_healthy
    networks:
      damap-internal:
        aliases:
          - damap-fe
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/" ]
      start_period: 120s
      interval: 30s
      timeout: 15s
      retries: 5

  proxy:
    image: nginx:1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - logs:/var/log
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
    secrets:
      - certificate
      - private_key
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      damap-internal:
      damap-external:
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/q/health/live" ]
      start_period: 120s
      interval: 30s
      timeout: 15s
      retries: 5

configs:
  nginx:
    content: |
      worker_processes  auto;
      error_log  /var/log/nginx/error.log notice;
      pid        /var/run/nginx.pid;
      events {
          worker_connections  1024;
      }
      http {
          include       /etc/nginx/mime.types;
          default_type  application/octet-stream;
          log_format    main  '$$remote_addr - $$remote_user [$$time_local] "$$request" '
                              '$$status $$body_bytes_sent "$$http_referer" '
                              '"$$http_user_agent" "$$http_x_forwarded_for"';
          access_log          /var/log/nginx/access.log  main;
          sendfile            on;
          keepalive_timeout   65;
          server {
              listen 443      ssl default_server;
              listen [::]:443 ssl default_server;
              http2 on;
              ssl_certificate     /run/secrets/certificate;
              ssl_certificate_key /run/secrets/private_key;
              add_header Strict-Transport-Security "max-age=63072000" always;
              location / {
                  proxy_pass http://damap-fe:8080;
                  proxy_set_header Host $$host;
                  proxy_set_header X-Forwarded-Host $$host;
                  proxy_set_header X-Forwarded-Proto $$scheme;
                  proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
              }
              location /api/ {
                  proxy_pass http://damap-be:8080;
                  proxy_set_header Host $$host;
                  proxy_set_header X-Forwarded-Host $$host;
                  proxy_set_header X-Forwarded-Proto $$scheme;
                  proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
              }
              location /q/swagger-ui {
                  proxy_pass http://damap-be:8080;
                  proxy_set_header Host $$host;
                  proxy_set_header X-Forwarded-Host $$host;
                  proxy_set_header X-Forwarded-Proto $$scheme;
                  proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
              }
              location /q/openapi {
                  proxy_pass http://damap-be:8080;
                  proxy_set_header Host $$host;
                  proxy_set_header X-Forwarded-Host $$host;
                  proxy_set_header X-Forwarded-Proto $$scheme;
                  proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
              }
              # TODO find a way to conditionally apply these only:
              location /realms {
                  proxy_pass http://keycloak:8080;
                  proxy_set_header Host $$host;
                  proxy_set_header X-Forwarded-Host $$host;
                  proxy_set_header X-Forwarded-Proto $$scheme;
                  proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
              }
              location /resources {
                  proxy_pass http://keycloak:8080;
                  proxy_set_header Host $$host;
                  proxy_set_header X-Forwarded-Host $$host;
                  proxy_set_header X-Forwarded-Proto $$scheme;
                  proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
              }
          }
          server {
              listen 80      default_server;
              listen [::]:80 default_server;
              location /api/ {
                  # Prevent the API from silently redirecting as the credentials may have been leaked:
                  return 400;
              }
              return 301 https://$$host$$request_uri;
          }

          # TLS configuration based on the Mozilla modern profile
          ssl_protocols TLSv1.3;
          ssl_ecdh_curve X25519:prime256v1:secp384r1;
          ssl_prefer_server_ciphers off;

          # Note: OCSP stapling is disabled as OCSP is being phased out,
          # see: https://letsencrypt.org/2024/12/05/ending-ocsp/
      }

  pure-persons-data:
    content: |
      {
        "count": 10,
        "pageInformation": {
          "offset": 0,
          "size": 50
        },
        "items": [
          {
            "uuid": "123456",
            "name": { "firstName": "Alice", "lastName": "Faketon" },
            "orcid": "0000-0000-0000-0001",
            "email": "alice.faketon@example.com"
          },
          {
            "uuid": "22222222-2222-2222-2222-222222222222",
            "name": { "firstName": "Bob", "lastName": "Mockman" },
            "orcid": "0000-0000-0000-0002",
            "email": "bob.mockman@example.com"
          }
        ]
      }

  pure-projects-data:
    content: |
      {
        "count": 2,
        "pageInformation": {
          "offset": 0,
          "size": 50
        },
        "items": [
          {
            "typeDiscriminator": "AwardManagementProject",
            "uuid": "ae91d2be-99a4-4d12-b172-a13ae282d808",
            "acronym": "Test",
            "participants": [
              {
                "typeDiscriminator": "InternalParticipantAssociation",
                "pureId": "1234",
                "name": {
                  "firstName": "Alice",
                  "lastName": "Faketon"
                },
                "role": {
                  "uri": "/dk/atira/pure/upmproject/roles/upmproject/pi",
                  "term": {
                    "de_AT": "Projektleitung",
                    "en_GB": "Principal Investigator",
                    "de_DE": "Projektleitung"
                  }
                },
                "person": {
                  "systemName": "Person",
                  "uuid": "123456"
                },
                "organizations": [
                  {
                    "systemName": "Organization",
                    "uuid": "777530ec-d1a5-49d3-bf65-b4c3a683ddcc"
                  }
                ]
              }
            ],
            "descriptions": [
              {
                "pureId": "123456",
                "value": {
                  "en_GB": "This is a test project"
                },
                "type": {
                  "uri": "/dk/atira/pure/upmproject/descriptions/projectdescription",
                  "term": {
                    "en_GB": "Description",
                    "de_DE": "Beschreibung"
                  }
                }
              },
              {
                "pureId": "987654321",
                "type": {
                  "uri": "/dk/atira/pure/upmproject/descriptions/keyfindings",
                  "term": {
                    "en_GB": "Key findings",
                    "de_DE": "Wichtigste Erkenntnisse"
                  }
                }
              }
            ],
            "period": {
              "startDate": "2022-01-01",
              "endDate": "2023-01-01"
            },
            "title": {
              "en_GB": "Test Project, Test",
              "de_DE": "Test Projekt, Test"
            },
            "systemName": "Project"
          },
          {
            "typeDiscriminator": "AwardManagementProject",
            "uuid": "ae91d2be-99a4-4d12-b172-a13ae282d809",
            "acronym": "Test2",
            "participants": [
              {
                "typeDiscriminator": "InternalParticipantAssociation",
                "pureId": "5678",
                "name": {
                  "firstName": "Bob",
                  "lastName": "Mockman"
                },
                "role": {
                  "uri": "/dk/atira/pure/upmproject/roles/upmproject/pi",
                  "term": {
                    "de_AT": "Projektleitung",
                    "en_GB": "Principal Investigator",
                    "de_DE": "Projektleitung"
                  }
                },
                "person": {
                  "systemName": "Person",
                  "uuid": "22222222-2222-2222-2222-222222222222"
                },
                "organizations": [
                  {
                    "systemName": "Organization",
                    "uuid": "88888888-d1a5-49d3-bf65-b4c3a683ddcc"
                  }
                ]
              }
            ],
            "descriptions": [
              {
                "pureId": "22222222",
                "value": {
                  "en_GB": "This is another test project"
                },
                "type": {
                  "uri": "/dk/atira/pure/upmproject/descriptions/projectdescription",
                  "term": {
                    "en_GB": "Description",
                    "de_DE": "Beschreibung"
                  }
                }
              },
              {
                "pureId": "987654322",
                "type": {
                  "uri": "/dk/atira/pure/upmproject/descriptions/keyfindings",
                  "term": {
                    "en_GB": "Key findings",
                    "de_DE": "Wichtigste Erkenntnisse"
                  }
                }
              }
            ],
            "period": {
              "startDate": "2023-01-01",
              "endDate": "2024-01-01"
            },
            "title": {
              "en_GB": "Test Project 2, Test",
              "de_DE": "Test Projekt 2, Test"
            },
            "systemName": "Project"
          }
        ]
      }

secrets:
  certificate:
    file: ./tls/bundle.crt
  private_key:
    file: ./tls/private.pem

volumes:
  logs:
    name: logs
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${PROXY_LOG_HOST_PATH?Please specify a log path.}"

networks:
  damap-external:
    name: damap-external
  damap-internal:
    name: damap-internal
    internal: true
