{{- if .Values.damap.create_pv }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: damap-db
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: "{{ .Values.damap.storage_class_name }}"
  claimRef:
    namespace: "{{ .Release.Namespace }}"
    name: damap-db
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "{{ .Values.damap.host_folder }}"
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: damap-db
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  storageClassName: "{{ .Values.damap.storage_class_name }}"
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: damap-backend
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: damap-backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: damap-backend
  template:
    metadata:
      labels:
        app: damap-backend
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      volumes:
        - name: damap
          secret:
            secretName: damap
{{- if .Values.pure.enabled }}
        - name: pure
          secret:
            secretName: damap-pure
{{- end }}
      containers:
        - name: damap-backend
          image: "{{ .Values.damap.backend_image }}"
          {{- if or (hasSuffix ":latest" .Values.damap.backend_image) (hasSuffix ":next" .Values.damap.backend_image) }}
          imagePullPolicy: Always
          {{- end }}
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              cpu: 10m
              memory: 2G
            limits:
              memory: 2G
              cpu: "0.25"
          ports:
            - containerPort: 9000
          env:
            - name: QUARKUS_HTTP_PORT
              value: "9000"
            - name: DAMAP_FITS_URL
              value: ""
            - name: DAMAP_GOTENBERG_URL
              value: "http://localhost:3000"
            - name: DAMAP_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: damap
                  key: db_username
            - name: DAMAP_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: damap
                  key: db_password
            - name: DAMAP_DATASOURCE_URL
              value: "jdbc:postgresql://damap-db:5432/{{ .Values.damap.db_name }}"
            - name: DAMAP_AUTH_BACKEND_CLIENT
              valueFrom:
                secretKeyRef:
                  name: damap
                  key: backend_auth_client_id
            - name: DAMAP_AUTH_FRONTEND_CLIENT
              valueFrom:
                secretKeyRef:
                  name: damap
                  key: frontend_auth_client_id
{{- if .Values.keycloak.deploy }}
            - name: DAMAP_AUTH_BACKEND_URL
{{- if eq .Values.keycloak.hostname "localhost" }}
              value: "http://keycloak:8080/realms/damap"
{{- else }}
              value: "{{ .Values.keycloak.protocol }}://{{ .Values.keycloak.hostname }}/realms/damap"
{{- end }}
            - name: DAMAP_AUTH_FRONTEND_URL
              value: "{{ .Values.keycloak.protocol }}://{{ .Values.keycloak.hostname }}/realms/damap"
{{- else }}
            - name: DAMAP_AUTH_USER
              value: "{{ .Values.oidc.person_id_claim }}"
            - name: DAMAP_AUTH_SCOPE
              value: "{{ .Values.oidc.scope | join " " }}"
            - name: DAMAP_AUTH_BACKEND_CLIENT
              value: "{{ .Values.oidc.backend_client_id }}"
            - name: DAMAP_AUTH_FRONTEND_CLIENT
              value: "{{ .Values.oidc.frontend_client_id }}"
            - name: DAMAP_AUTH_BACKEND_URL
              value: "{{ .Values.oidc.backend_endpoint }}"
            - name: DAMAP_AUTH_FRONTEND_URL
              value: "{{ .Values.oidc.frontend_endpoint }}"
{{- end }}
            - name: DAMAP_ORIGINS
              value: "{{ .Values.damap.protocol }}://{{ .Values.damap.hostname }}"
            - name: DAMAP_ENV
              value: "{{ if eq .Values.debug true }}DEV{{ else }}PROD{{ end }}"
{{- if .Values.pure.enabled }}
            - name: DAMAP_PROJECTS_SERVICE
              value: elsevier-pure
            - name: DAMAP_ELSEVIER_PURE_BACKEND
              value: "{{ .Values.pure.backend }}"
            - name: DAMAP_ELSEVIER_PURE_PROJECTS_FILE
              value: file:///data/projects.json
            - name: DAMAP_ELSEVIER_PURE_PERSONS_FILE
              value: file:///data/persons.json
            - name: DAMAP_ELSEVIER_PURE_ENDPOINT_URL
              value: "{{ .Values.pure.endpoint }}"
            - name: DAMAP_ELSEVIER_PURE_API_KEY
              value: "{{ .Values.pure.api_key }}"
            - name: DAMAP_ELSEVIER_PURE_DESCRIPTION_CLASSIFICATION
              value: {{ .Values.pure.description_classification | quote }}
            - name: DAMAP_ELSEVIER_PURE_PROJECT_LEAD_ROLE_CLASSIFICATION
              value: {{ .Values.pure.project_lead_classification | quote }}
            - name: DAMAP_ELSEVIER_PURE_CONTRIBUTOR_ROLE_CLASSIFICATIONS
              value: {{ .Values.pure.role_classifications | toJson | quote }}
            - name: DAMAP_PERSON_SERVICES
              value: "[{\"display-text\": \"Pure\", \"query-value\": \"PURE\", \"class-name\": \"org.damap.base.integration.pure.PurePersonService\"}]"
{{- end }}
          volumeMounts:
{{- if .Values.pure.enabled }}
            - mountPath: /data/persons.json
              name: pure
              readOnly: true
              subPath: persons.json
            - mountPath: /data/projects.json
              name: pure
              readOnly: true
              subPath: projects.json
{{- end }}
            # Workaround for reaugmentation write permissions:
            - mountPath: /quarkus-app/.db_kind
              name: damap
              readOnly: true
              subPath: db_kind
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 9000
            initialDelaySeconds: 600
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - "ALL"
        - name: gotenberg
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - "ALL"
          image: gotenberg/gotenberg:8
          resources:
            requests:
              cpu: 10m
              memory: 512Mi
            limits:
              memory: 2G
              cpu: "0.25"
---
apiVersion: v1
kind: Service
metadata:
  name: damap-backend
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: damap-backend
spec:
  selector:
    app: damap-backend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: damap-frontend
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: damap-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: damap-frontend
  template:
    metadata:
      labels:
        app: damap-frontend
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      {{- if .Values.frontend.customize }}
      volumes:
        - name: damap-customization
          secret:
            secretName: damap-customization
      {{- end }}
      containers:
        - name: damap-frontend
          image: "{{ .Values.damap.frontend_image }}"
          {{- if or (hasSuffix ":latest" .Values.damap.backend_image) (hasSuffix ":next" .Values.damap.backend_image) }}
          imagePullPolicy: Always
          {{- end }}
          {{- if .Values.frontend.customize }}
          volumeMounts:
            - mountPath: /usr/share/nginx/html/assets/logo-cropped.svg
              name: damap-customization
              subPath: logo-cropped.svg
              readOnly: true
            - mountPath: /usr/share/nginx/html/assets/logo.svg
              name: damap-customization
              subPath: logo.svg
              readOnly: true
          {{- end }}
          resources:
            requests:
              cpu: 10m
              memory: 512Mi
            limits:
              memory: 512Mi
              cpu: "0.5"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - "ALL"
---
apiVersion: v1
kind: Service
metadata:
  name: damap-frontend
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: damap-frontend
spec:
  selector:
    app: damap-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: damap-db
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: damap-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: damap-db
  template:
    metadata:
      labels:
        app: damap-db
    spec:
      securityContext:
        {{- if .Values.openshift }}
        runAsNonRoot: true
        {{- end }}
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      volumes:
        - name: damap-db
          persistentVolumeClaim:
            claimName: damap-db
      containers:
        - name: damap-db
          image: postgres:16
          resources:
            requests:
              cpu: 10m
              memory: 512Mi
            limits:
              memory: 2G
              cpu: "0.25"
          {{- if .Values.damap.create_pv }}
          volumeMounts:
            - name: damap-db
              mountPath: /var/lib/postgresql/data
          {{- end }}
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/damap-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: damap
                  key: db_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: damap
                  key: db_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: damap
                  key: db_database
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - /usr/bin/pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- if .Values.openshift }}
          securityContext:
            runAsNonRoot: true
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: damap-db
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: damap-db
spec:
  selector:
    app: damap-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
