{{- if .Values.keycloak.deploy }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: "{{ .Release.Namespace }}"
  annotations:
    {{- if and (eq .Values.keycloak.protocol "https") (.Values.keycloak.tls_issuer) }}
    cert-manager.io/cluster-issuer: {{ .Values.keycloak.tls_issuer | quote }}
    {{- end }}
    {{- if .Values.openshift }}
    haproxy.router.openshift.io/hsts_header: "max-age=31536000;includeSubDomains;preload"
    {{- end }}
spec:
  {{- if .Values.keycloak.ingress_class }}
  ingressClassName: {{ .Values.keycloak.ingress_class }}
  {{- end }}
  {{- if eq .Values.keycloak.protocol "https" }}
  tls:
    - hosts:
        - {{ .Values.keycloak.hostname | quote }}
      secretName: keycloak-tls
  {{- end }}
  rules:
    - host: {{ .Values.keycloak.hostname | quote }}
      http:
        paths:
          - path: "{{ if eq .Values.keycloak.hostname "localhost" }}/realms{{ else }}/{{ end }}"
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          {{- if eq .Values.keycloak.hostname "localhost" }}
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - path: "/resources"
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          {{- end }}
{{- end }}
