apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: damap
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if and (eq .Values.damap.protocol "https") (.Values.damap.tls_issuer) }}
    cert-manager.io/cluster-issuer: {{ .Values.damap.tls_issuer | quote }}
    {{- end }}
    {{- if .Values.openshift }}
    haproxy.router.openshift.io/hsts_header: "max-age=31536000;includeSubDomains;preload"
    {{- end }}
spec:
  {{- if .Values.ingress_class }}
  ingressClassName: {{ .Values.ingress_class }}
  {{- end }}
  {{- if eq .Values.damap.protocol "https" }}
  tls:
    - hosts:
        - {{ .Values.damap.hostname | quote }}
      secretName: damap-tls
  {{- end }}
  rules:
    - host: {{ .Values.damap.hostname | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: damap-backend
                port:
                  number: 9000
          - path: /q/swagger-ui
            pathType: Prefix
            backend:
              service:
                name: damap-backend
                port:
                  number: 9000
          - path: /q/openapi
            pathType: Prefix
            backend:
              service:
                name: damap-backend
                port:
                  number: 9000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: damap-frontend
                port:
                  number: 8080
